"""Trait-based interface for burst dispatch pools.
"""

from std.memory import UnsafePointer
from .threading_shared import ArgPack


trait BurstThreadPool(Movable, ImplicitlyDestructible):
    def get_capacity(self) -> Int: ...
    def get_args_base(self) -> UnsafePointer[ArgPack, MutAnyOrigin]: ...

    def dispatch[F: TrivialRegisterPassable](mut self, kernel: F,
        packs: UnsafePointer[ArgPack, MutAnyOrigin], num_jobs: Int): ...

    def join(mut self): ...

    def last_worker_timestamp(self) -> Int: ...


trait SleepableThreadPool:
    def wake(mut self): ...
    def sleep(mut self): ...
